# Generated by Django 2.0.13 on 2019-10-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_auto_20191024_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='resumen_notica',
            new_name='resumen_noticia',
        ),
    ]
