# Generated by Django 2.0.13 on 2019-10-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion_medica',
            name='altura',
            field=models.FloatField(verbose_name='Altura del niño (Metros)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_medica',
            name='circunferencia_abdominal',
            field=models.FloatField(verbose_name='Circunferencia abdominal (Centímetros)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_medica',
            name='circunferencia_brazo_derecho',
            field=models.FloatField(verbose_name='Circunferencia del brazo derecho (Centímetros)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_medica',
            name='circunferencia_brazo_izquierdo',
            field=models.FloatField(verbose_name='Circunferencia del brazo izquierdo (Centímetros)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_medica',
            name='peso',
            field=models.IntegerField(verbose_name='Peso del niño (Libras)'),
        ),
    ]
