# Generated by Django 2.0.13 on 2019-10-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_doctor', '0002_auto_20191020_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion_medica',
            name='medico',
            field=models.CharField(default='asd', max_length=40, verbose_name='Doctor encargado de la evaluación'),
        ),
    ]
