# Generated by Django 2.0.13 on 2019-10-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_doctor', '0003_evaluacion_medica_medico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion_medica',
            name='medico',
            field=models.CharField(max_length=40, verbose_name='Doctor encargado de la evaluación'),
        ),
    ]
