# Generated by Django 2.0.13 on 2019-11-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_doctor', '0004_auto_20191023_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion_medica',
            name='antecendentes_medicos',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes médicos de importancia'),
        ),
        migrations.AlterField(
            model_name='evaluacion_medica',
            name='imc',
            field=models.FloatField(blank=True, null=True, verbose_name='I.M.C (Indice de masa corporal)'),
        ),
        migrations.AlterField(
            model_name='evaluacion_medica',
            name='padece_alergias',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Padece de alergias, cual'),
        ),
        migrations.AlterField(
            model_name='evaluacion_medica',
            name='sintomas',
            field=models.TextField(blank=True, null=True, verbose_name='Síntomas'),
        ),
    ]
