# Generated by Django 2.0.13 on 2019-10-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0002_auto_20191014_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_medica',
            name='altura',
            field=models.FloatField(verbose_name='Altura del niño (Metros)'),
        ),
        migrations.AlterField(
            model_name='area_medica',
            name='peso',
            field=models.IntegerField(verbose_name='Peso del niño (Libras)'),
        ),
    ]
