# Generated by Django 2.0.13 on 2019-10-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0003_auto_20191020_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivo_ingreso',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='nna',
            name='descripcion_motivo',
            field=models.TextField(default='asd', verbose_name='Descripción del motivo de ingreso'),
        ),
        migrations.AddField(
            model_name='nna',
            name='juzgado_refiere',
            field=models.CharField(blank=True, choices=[('Ay', 'Ayutla'), ('Sm', 'San Marcos'), ('Ca', 'Catarina'), ('Cm', 'Comitancillo'), ('Ct', 'Concepción Tutuapa'), ('Eq', 'El Quetzal'), ('Et', 'El Tumbador'), ('Ep', 'Esquipulas Palo Gordo'), ('Ix', 'Ixchiguan'), ('Lb', 'La Blanca'), ('Lr', 'La Reforma'), ('M', 'Malacatán'), ('Np', 'Nuevo Progreso'), ('O', 'Ocós'), ('P', 'Pajapita'), ('R', 'Río Blanco'), ('Sac', 'San Antornio Sac.'), ('Scc', 'San Cristóbal Cucho'), ('Sr', 'San José el Rodeo'), ('So', 'San José Ojetenam'), ('Sl', 'San Lorenzo'), ('Sx', 'San Miguel Ixtahuacán'), ('Sjr', 'San José el Rodeo'), ('Sp', 'San Pablo'), ('Spc', 'San Pedro Sac.'), ('Srp', 'San Rafael pie de la Cuesta'), ('S', 'Sibinal'), ('Si', 'Sipacapa'), ('T', 'Tacaná'), ('Tj', 'Tajumulco'), ('Tja', 'Tejutla')], max_length=4, null=True, verbose_name='Juzgado que refiere al niño'),
        ),
        migrations.AlterField(
            model_name='nna',
            name='cui',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='CUI'),
        ),
        migrations.AlterField(
            model_name='nna',
            name='grado_educativo',
            field=models.CharField(blank=True, choices=[('Pr', 'Pre-Primario'), ('P', 'Primario'), ('Ba', 'Básico'), ('D', 'Diversificado'), ('Na', 'Ninguno')], max_length=30, null=True, verbose_name='Nivel educativo'),
        ),
    ]
