# Generated by Django 2.0.13 on 2019-10-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0004_auto_20191022_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nna',
            name='descripcion_motivo',
            field=models.TextField(verbose_name='Descripción del motivo de ingreso'),
        ),
    ]
