# Generated by Django 2.0.13 on 2019-10-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0005_auto_20191022_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='nna',
            name='orden_ingreso',
            field=models.FileField(default='asd', upload_to='img', verbose_name='Adjunte la orden de ingreso'),
        ),
    ]
