# Generated by Django 2.0.13 on 2019-10-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0006_nna_orden_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nna',
            name='orden_ingreso',
            field=models.FileField(upload_to='img', verbose_name='Orden de ingreso'),
        ),
    ]
