# Generated by Django 2.0.13 on 2019-10-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0007_auto_20191022_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='nna',
            name='certificado_nacimiento',
            field=models.ImageField(default='asd', upload_to='img', verbose_name='Certificado de nacimiento'),
        ),
    ]
