# Generated by Django 2.0.13 on 2019-10-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0008_nna_certificado_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enfermedad',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='fuente_estre',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='area_psicologica',
            name='descripcion',
            field=models.TextField(default='asd', verbose_name='Descripcion de la enfermedad psicológica'),
        ),
        migrations.AddField(
            model_name='area_social',
            name='descripcion',
            field=models.TextField(default='sas', verbose_name='Descripción de la fuente de estrés'),
        ),
    ]
