# Generated by Django 2.0.13 on 2019-10-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0009_auto_20191023_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_psicologica',
            name='descripcion',
            field=models.TextField(verbose_name='Descripcion de la enfermedad psicológica'),
        ),
        migrations.AlterField(
            model_name='area_social',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción de la fuente de estrés'),
        ),
    ]
