# Generated by Django 2.0.13 on 2019-11-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0010_auto_20191023_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='nna',
            name='oficial',
            field=models.CharField(choices=[('fr', '1ro'), ('sd', '2do'), ('tr', '3ro'), ('fr', '4to'), ('N', 'Ninguno')], default=1, max_length=4, verbose_name='Oficial'),
        ),
    ]
