# Generated by Django 2.0.13 on 2019-11-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0012_auto_20191109_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nna',
            name='certificado_nacimiento',
            field=models.FileField(upload_to='img', verbose_name='Certificado de nacimiento (Archivo .pdf)'),
        ),
        migrations.AlterField(
            model_name='nna',
            name='orden_ingreso',
            field=models.FileField(upload_to='img', verbose_name='Orden de ingreso (Archivo .pdf)'),
        ),
    ]
