# Generated by Django 2.0.13 on 2019-11-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0013_auto_20191109_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='nna',
            name='no_expediente',
            field=models.IntegerField(default='000', verbose_name='Número de expediente'),
        ),
    ]
