# Generated by Django 2.0.13 on 2019-11-10 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0014_nna_no_expediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nna',
            name='no_expediente',
            field=models.IntegerField(verbose_name='Número de expediente'),
        ),
    ]
