# Generated by Django 2.0.13 on 2019-11-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0015_auto_20191109_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='nna',
            name='fecha_resolucion',
            field=models.DateField(default='1', verbose_name='Fecha de resolución'),
        ),
    ]
