# Generated by Django 2.0.13 on 2019-11-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0016_nna_fecha_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nna',
            name='fecha_resolucion',
            field=models.DateField(default='20/11/2019', verbose_name='Fecha de resolución'),
        ),
    ]
