# Generated by Django 2.0.13 on 2019-11-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0017_auto_20191109_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nna',
            name='fecha_resolucion',
            field=models.CharField(default='20/11/2019', max_length=30, verbose_name='Fecha de resolución'),
        ),
    ]
