# Generated by Django 2.0.13 on 2019-11-10 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0019_auto_20191109_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nna',
            name='fecha_resolucion',
        ),
    ]
