# Generated by Django 2.0.13 on 2019-11-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0020_remove_nna_fecha_resolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='nna',
            name='otro_dato',
            field=models.CharField(default='...', max_length=60),
        ),
    ]
