# Generated by Django 2.0.13 on 2019-11-10 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0022_auto_20191109_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nna',
            name='otro_dato',
        ),
    ]
