# Generated by Django 2.0.13 on 2019-11-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0023_remove_nna_otro_dato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_dental',
            name='diagnostico',
            field=models.TextField(blank=True, null=True, verbose_name='Dignóstico'),
        ),
        migrations.AlterField(
            model_name='area_dental',
            name='intervencion',
            field=models.TextField(blank=True, null=True, verbose_name='Intervención médica'),
        ),
        migrations.AlterField(
            model_name='area_psicologica',
            name='aspecto_clinico',
            field=models.TextField(default='...', verbose_name='Aspecto clínico'),
        ),
        migrations.AlterField(
            model_name='area_psicologica',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion de la enfermedad psicológica'),
        ),
        migrations.AlterField(
            model_name='area_psicologica',
            name='estado_emocional',
            field=models.TextField(blank=True, null=True, verbose_name='Estado emocional'),
        ),
        migrations.AlterField(
            model_name='area_psicologica',
            name='percepcion_temores_actuales',
            field=models.TextField(blank=True, null=True, verbose_name='Percepción de temores actuales'),
        ),
        migrations.AlterField(
            model_name='area_psicologica',
            name='percepcion_temores_futuros',
            field=models.TextField(blank=True, null=True, verbose_name='Percepción de temores futuros'),
        ),
        migrations.AlterField(
            model_name='area_social',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la fuente de estrés'),
        ),
    ]
