# Generated by Django 2.0.13 on 2019-11-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0024_auto_20191110_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area_psicologica',
            name='aspecto_clinico',
            field=models.TextField(verbose_name='Aspecto clínico'),
        ),
    ]
