# Generated by Django 2.0.13 on 2019-11-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nino', '0025_auto_20191110_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nna',
            name='certificado_nacimiento',
            field=models.FileField(upload_to='doc', verbose_name='Certificado de nacimiento (Archivo .pdf)'),
        ),
        migrations.AlterField(
            model_name='nna',
            name='image',
            field=models.ImageField(upload_to='doc', verbose_name='Fotografía del niño'),
        ),
        migrations.AlterField(
            model_name='nna',
            name='orden_ingreso',
            field=models.FileField(upload_to='doc', verbose_name='Orden de ingreso (Archivo .pdf)'),
        ),
    ]
